##############
# PARAMETERS #
##############
input_directory: '/mnt/motus_db/genomes'
output_directory: '/home/ubuntu/lilith/mining_crispr_pipeline_results'
pam_predict_installation_directory: '/home/ubuntu/lilith/PAMpredict/PAMpredict'
hmm_files_path: '/mnt/Profiles'
sample_file: '/home/ubuntu/lilith/Mining_CRISPR/snakemake_pipeline/config/samples'
phage_database: '/mnt/Valentyn_deduplicate_plusPR/combined.fna'
cas_type: 'cas9'
num_processes: 2

################
# RULES TO RUN #
################
# The pipeline expects your data to be gzipped
run_minced: True
run_pilercr: True
run_merge: True
run_clustering: True
run_prepare_spacers: True
run_pam_predict: False