##############
# PARAMETERS #
##############
input_directory: '/path/to/fastas' # path to the database of gzipped fasta files
output_directory: '/path/to/results' # where your results should be
pam_predict_installation_directory: '/path/to/PAMpredict/PAMpredict' # absolute path to PAMpredict installation directory
hmm_files_path: '/path/to/hmm/profiles' # path to hmm profiles
sample_file: '/path/to/CRISPR-PAMdb/snakemake_pipeline/samples' # path to samples file
phage_database: '/path/to/phages.fna' # path to the fasta file of your phage database
cas_type: 'cas9' # cas type you are interested in
num_processes: '2' # to speed up PAMpredict, may lead to errors if number is chosen too high

################
# RULES TO RUN #
################
# The pipeline expects your data to be gzipped
run_minced: True
run_pilercr: True
run_merge: True
run_clustering: True
run_pam_predict: True
